# Generated by Django 5.1.4 on 2025-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_new_followers_userinsights_current_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsights',
            name='new_followers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userinsights',
            name='new_follows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
