# Generated by Django 5.1.4 on 2025-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinsights_new_followers_userinsights_new_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinsights',
            old_name='old_followers',
            new_name='previous_followers',
        ),
        migrations.RenameField(
            model_name='userinsights',
            old_name='old_followings',
            new_name='previous_followings',
        ),
        migrations.RenameField(
            model_name='userinsights',
            old_name='old_unfollowers',
            new_name='previous_new_followers',
        ),
        migrations.RenameField(
            model_name='userinsights',
            old_name='old_unfollows',
            new_name='previous_new_follows',
        ),
        migrations.AddField(
            model_name='userinsights',
            name='previous_unfollowers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userinsights',
            name='previous_unfollows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
