# Generated by Django 5.1.4 on 2025-01-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_old_followers_userinsights_previous_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsights',
            name='fans',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userinsights',
            name='non_followers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
