# Generated by Django 5.1.4 on 2025-01-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinsights_fans_userinsights_non_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsights',
            name='latest_file_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinsights',
            name='previous_file_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
